// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLogo: typeof import('./../components/AppLogo/index.vue')['default']
    BackToTop: typeof import('./../components/BackToTop/index.vue')['default']
    CustomLink: typeof import('./../components/CustomLink/index.vue')['default']
    LangSwitcher: typeof import('./../components/LangSwitcher/index.vue')['default']
    NaiveProvider: typeof import('./../components/NaiveProvider/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenLoader: typeof import('./../components/ScreenLoader/index.vue')['default']
    ThemeSwitcher: typeof import('./../components/ThemeSwitcher/index.vue')['default']
    UserProfile: typeof import('./../components/UserProfile/index.vue')['default']
  }
}
